spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3307/gwent
    password: 12345
    username: root
    hikari:
      maximum-pool-size: 100

ru:
  homyakin:
    gwent:
      telegram:
        bot:
          token: "stab"
          username: "stab"